# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SQL-Biblosoph
version:      1.2
version_from: lib/SQL/Bibliosoph.pm
installdirs:  site
requires:
    Carp:                          
    DBD::mysql:                    4.004
    DBI:                           1.5
    Object::InsideOut:             
    Package::Constants:            
    Test::More:                    

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
